# Generated by Django 4.2.30 on 2026-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='employer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
