# Generated by Django 4.2.30 on 2026-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
